## Applications plugin yml

name: Applications
version: 2013b-1.6.2-dev
description: Bewerbungen fuer schoene Bauwerke um hoeheren Rang zu bekommen
author: prosicraft
website: http://www.mineandcraft.de

main: com.prosicraft.applications.Applications

commands:
    apply:
        description: Bewerbungen verwalten
        usage: /<command> <open|close|vote|warp> [ID [Wert]]
        permission: applications.apply
        aliases: [bewerbung, app]       